### ISSUE TITLE
pass credentials for github

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#110]
Building all the codes times out because [github rate limits unauthenticated accesses](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) to 60 per hour instead of 5000 for authenticated users. First step is to verify this. If so, then add importing of the GitHub PAT inside the containers (can be an env var import possibly in install_export_vars).

**Comment by e-carlin** [comment]
I don't know that the numbers are right but in my own testing, unrelated to building all codes, when I add my creds the rate limit error goes away.

**Comment by robnagler** [comment]
I don't know how the rate limit works with git clone. Builds use api.github.com so we need to use a .netrc which passes that (maybe it does if the host is github.com).

**Comment by robnagler** [comment]
Done.
