### ISSUE TITLE
20221123 radia_run container-build failing for fedora36

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#111]
On a relatively clean Fedora 32 VM you can't run radia_run container-build. It fails inside the docker build trying to do a git clone of home-env, which seems to be the first network reference. It's trying to build in side fedora-36. When setting install_version_fedora=36, the build worked.

Not a 100% sure what's going on here.

**Comment by e-carlin** [comment]
Are you trying to build a fedora 36 or 32 image?

**Comment by robnagler** [comment]
I was trying to build a 32 image at first.

**Comment by e-carlin** [comment]
Ok, can you send me steps to reproduce for building a fedora 32 image from a fedora 32 vm? I was able to build just now
```bash
$ grep -i '^version=' /etc/os-release
VERSION="32 (Cloud Edition)"
$ cd ~/src/radiasoft/container-fedora/
container-fedora (master)$ install_version_fedora=32 install_version_python=3.7.2 radia_run container-build
<snip>
Successfully tagged radiasoft/fedora:20221128.172432
```

FWIW building a fedora 36 image on a fedora 32 vm will work. We've run into some issues before https://github.com/radiasoft/devsecops/issues/116 . That issue is seen when trying to make network requests.

**Comment by robnagler** [comment]
$ cd ~/src/radiasoft
$ gcl container-sirepo-e2e
$ cd container-sirepo-e2e
$ git checkout playwright
$ radia_run container-build
Log: /home/vagrant/src/radiasoft/container-sirepo-e2e/radia-run-install.log
curl -L -s -S https://api.github.com/repos/radiasoft/download/contents/installers/container-build/radiasoft-download.sh
Source: /var/tmp/radia-run-541604-25940/20221128204233-radiasoft-download.sh
curl -L -s -S https://api.github.com/repos/radiasoft/containers/contents/radiasoft-download.sh
Source: /var/tmp/radia-run-541604-7014/20221128204233-radiasoft-download.sh
curl -L -s -S https://api.github.com/repos/radiasoft/containers/contents/bin/build.sh
Source: /var/tmp/radia-run-541604-7014/20221128204233-build.sh
curl -L -s -S https://api.github.com/repos/radiasoft/containers/contents/bin/build-docker.sh
Source: /var/tmp/radia-run-541604-7014/20221128204234-build-docker.sh
Conf: /home/vagrant/src/radiasoft/container-sirepo-e2e/container-conf
Build: /var/tmp/containers-20221128.204234-17976
Sending build context to Docker daemon  53.25kB
Step 1/7 : FROM radiasoft/fedora:fedora-36
fedora-36: Pulling from radiasoft/fedora

^[[1B
^[[1B
^[[1BDigest: sha256:444aa4425957db55d0bc77867721144bf4fee25e3ac9fe134d09f9ff9a693d36
Status: Downloaded newer image for radiasoft/fedora:fedora-36
 ---> 9be08957ccae
Step 2/7 : MAINTAINER "RadiaSoft <support@radiasoft.net>"
 ---> Running in 37770514e35a
Removing intermediate container 37770514e35a
 ---> 1c1739eebc5b
Step 3/7 : USER root
 ---> Running in 58b379811a69
Removing intermediate container 58b379811a69
 ---> 2aa20dcc40ae
Step 4/7 : ADD . /rscontainers
 ---> 49599988a137
Step 5/7 : RUN "/rscontainers/build-run.sh"
 ---> Running in 0a83b1c62cb5
^[[91mtouch /var/lib/rpm/*
^[[0m^[[91mUpdating: /root/src/biviosoftware/home-env
^[[0m^[[91mfatal: unable to access 'https://github.com/biviosoftware/home-env.git/': getaddrinfo() thread failed to start
^[[0mThe command '/bin/sh -c "/rscontainers/build-run.sh"' returned a non-zero code: 1
Build: ERROR TRAP
Directory: /var/tmp/containers-20221128.204234-17976
```

**Comment by e-carlin** [comment]
Thanks. Looks like you are building a fedora 36 based image. If you want to build a fedora 32 image you'll need to set `install_version_fedora=32 install_version_python=3.7.2` to override [the defaults](https://github.com/radiasoft/download/blob/7e31003aaacbf4a04317ab74c64eb8b16eddefc6/bin/install.sh#L201). 

If you want to build a fedora 36 image from fedora 32 you are SOL (well probably not, but I don't know how to resolve easily) per my comment above:

> FWIW building a fedora 36 image on a fedora 32 vm will work. We've run into some issues before https://github.com/radiasoft/devsecops/issues/116 . That issue is seen when trying to make network requests.

It looks like the issue you are seeing is the same as in the linked issue. There is some talk in the issue about the cause (maybe outdated glibc?) but I never got to the bottom of it. The easiest way I know to build a fedora 36 image is to do so from centos or from a fedora 36 vm.

**Comment by robnagler** [comment]
We don't need this.

**Comment by robnagler** [comment]
This is a security issue with fedora36 and/or ubuntu: https://openforums.blog/2021/12/15/tracing-curl-error-6-getaddrinfo-thread-failed-to-start-error-with-systemd-seccomp-filters/

**Comment by robnagler** [comment]
The general rule only applies to RHEL. This is Fedora.

[In a comment](https://bugzilla.redhat.com/show_bug.cgi?id=1990469#c8) 

> you would be running using Podman instead of Docker.

Not good. We are not switching to podman.

> Can you elaborate on the security implications?

It's in security code. Not a security problem.

> FWIW I think this is the [fix in docker](https://github.com/moby/moby/pull/42836/files).

This may not fix ubnt, but it will fix running fedora 36 vms.

**Comment by e-carlin** [comment]
> It's in security code. Not a security problem.

Ah ok.

> This may not fix ubnt, but it will fix running fedora 36 vms.

I'm not sure how ubuntu fits into the situation? Do we run fedora containers right on the ubuntu host? 

Is there something I should be addressing now that the issue has been re-opened? Or more of a "wait and see"?

**Comment by robnagler** [comment]
> I'm not sure how ubuntu fits into the situation? Do we run fedora containers right on the ubuntu host?

Yes for now.

> Is there something I should be addressing now that the issue has been re-opened?

We need to cap_add or something to make this happen so that container builds work on fedora 36. I don't think they do now.

**Comment by e-carlin** [comment]
> We need to cap_add or something to make this happen so that container builds work on fedora 36. I don't think they do now.

I believe they do. I just ran this on a fedora36 vm.
```
~$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Cloud Edition)"
<snip>
~$ cd ~/src/radiasoft/container-python3/
container-python3 (master)$ radia_run container-build
<snip>
Built: radiasoft/python3:20230110.231608
Channels: 20230110.231608 alpha dev latest fedora-36
To run it:

docker run --rm -it --network=host 'radiasoft/python3:20230110.231608'

After some testing, push:

docker push 'radiasoft/python3:20230110.231608'|tee;
docker push 'radiasoft/python3:alpha'|tee;
docker push 'radiasoft/python3:dev'|tee;
docker push 'radiasoft/python3:latest'|tee;
docker push 'radiasoft/python3:fedora-36'|tee;
container-python3 (master)$ docker run --rm -it --network=host 'radiasoft/python3:20230110.231608' bash -c 'cat /etc/os-release'
NAME="Fedora Linux"
VERSION="36 (Container Image)"
```

**Comment by robnagler** [comment]
It must fix the clone3  thing.

**Comment by e-carlin** [comment]
What's the status of this? I'm not sure I know what the bug is.

**Comment by robnagler** [comment]
No idea. Make sure we can build on 36 docker image on a 36 vm. I don't know that we are concerned with the cross compile case right now.

**Comment by e-carlin** [comment]
Confirmed
