### ISSUE TITLE
tar error on cygwin with Windows 10 Pro

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/containers#12]
With a fresh cygwin install on Windows 10 Pro, the following command
$ curl -s -S -L https://raw.githubusercontent.com/radiasoft/containers/master/bin/vagrant-up-dev | bash 
generates the following error message:
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.

**Comment by robnagler** [comment]
Not supporting cygwin.
