### ISSUE TITLE
VirtualBox fails due to bios settings on PC laptop

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/containers#13]
Hardware: HP Spectre 360 laptop
OS: Windows 10 Pro
Processor: Intel Core i7-6560U CU 2.20 GHz (dual)
System type: 64-bit OS, x64-based processor

The Vagrant file contains the following:
Vagrant.configure(2) do |config|
  config.vm.box = "radiasoft/develop"
  config.vm.hostname = "rsdev"
  config.ssh.forward_x11 = true
end

The following error is seen:
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'radiasoft/radtrack' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "9cb3b6e8-c8ab-4838-89e3-defa4ac7a6f7", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by robnagler** [comment]
What version of VirtualBox?

**Comment by bruhwile** [comment]
Oracle VirtualBox 5.0.16 r105871

Based on advice in online forums, I tried to solve the problem by modifying the VirtualBox settings as follows:

Machine -> Settings  (or just type ctrl-s)
select 'System'
select 'Processor'
unselect the box 'PAE/NX'

That didn't change the error.

Based on advice in online forums, I then tried to solve the problem by entering the BIOS editor, going to the Configuration panel, and enabling Virtualization.

This resolved the error, but then the following error was encountered:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'radiasoft/radtrack' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by bruhwile** [comment]
I modified the Vagrantfile as follows

Vagrant.configure(2) do |config|
  config.vm.box = "radiasoft/radtrack"
  config.vm.hostname = "rs"
  config.ssh.insert_key = false
  config.ssh.forward_x11 = true
  config.vm.network "private_network", ip: "10.10.10.10"
end

The same error occurs, but some details are different:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'radiasoft/radtrack' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by bruhwile** [comment]
Supposedly having Hyper V enabled on Windows can cause problems like this, so I verified that it is not enabled on my machine.

Firewalls can also be an issue, so I disabled this, but that did not seem to help.

I then tried the following:
> vagrant destroy
> vagrant up
which worked right away.

It appears that the box was in a bad state and had to be destroyed...
