### ISSUE TITLE
Add build version in container

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#18]
radiasoft/sirepo#128 needs build version. Add that to the container as an environ var which is then available in pykern.pkconfig.container_version (or something like that).

**Comment by robnagler** [comment]
/radia.yml should look like:

```yaml
---
radia_version: yyyymmdd.hhmmss
```

For now, this has only one value, but eventually will have all the versions.

**Comment by elventear** [comment]
I don't understand the requirements fully. Besides making the environ variable available, do I need to make `pykern.pkconfig.container_version` this always available via Pykern? Or should I modify Sirepo? Or someone else will do that once the build process is fixed?

What about Vagrant? Should the environment variable also be available when building Vagrant images?

**Comment by elventear** [comment]
Commited initial stab at fixing the issue.

**Comment by elventear** [comment]
Instead of environment variable added functionality to create `/RSMANIFEST.yml` on all containers.
