### ISSUE TITLE
create SRW-light repo to avoid tarball copy

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#22]
The standard SRW repo is over 600MB, and GitHub sometimes times out during clones. We created a tarball snapshot to avoid this issue, but now that we are having active development of SRW by @mrakitin , we need a solution that pulls from a repo so we'll create a trimmed down repo as is done with the create_srw_tar_gz function in beamsim/codes/srw.sh.

**Comment by robnagler** [comment]
Created https://github.com/radiasoft/SRW-light, which is used for builds now. Closed with 72e6554

**Comment by mrakitin** [comment]
Thanks Rob!
