### ISSUE TITLE
beamsim-jupyter: include emacs in the container

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/containers#32]
Please include emacs in the container.

In order to debug and develop IPy Notebooks on the server, it's necessary to 
- edit files
- pip install
- test
- push to GitHub

For example, I find I have to do this with rssynergia in order to get the notebooks working.
This is too painful with vi.

I don't need the GUI or X-version; command-line only version is fine, if that's helpful in terms of saving space.

**Comment by robnagler** [comment]
I think we can provide a value add here. I also have some questions:

* How do you like the Jupyter text file editor? It does have emacs
bindings. Is it too annoying to use going to the file browser?
* Would it be useful to have a button for checking out a github repo, or
maybe some other connection in the UI to GitHub?
* With GitHub, we can actually integrate to push into the repo. This would
be giving more permissions to the (web) app. Would you want this, or would
you want to type your credentials each time? You might be able to setup an
API key per repo, but if not, it would be granting to all repos.

The value add is: Improving the facilities for developing Python/etc. (not
notebook) apps in browser, similar to PyCharm but in a notebook style. It's
something that's missing from Jupyter.

There is an extension:

http://www.lab41.org/commit-and-push-to-github-from-jupyter-notebooks/

I haven't tried it, but I don't think it does enough. I think automation of
checkins would be useful. I also think there's something we could do with
automatic sharing of notebooks.

**Comment by bruhwile** [comment]
Just to be clear, I have Python source code on the server, which I want to
edit and then pip install, so an active Jupyter notebook can (after
restarting the kernel) import the modified library for testing. The library
happens to be in a GitHub repository, which is convenient but not
necessarily an essential aspect of the problem.

I'm using the Jupyter terminal window to interact with GitHub, to pip
install and, hopefully, to edit files.

My work around is to edit the files on my local machine and then
commit/push to GitHub.
Then, on the server, I git pull and pip install.
The work around is OK in most respects, but it requires me to push broken
changes to the repo so I can test them live on the server.
Maybe there are better work arounds, but I thought it would be convenient
to have emacs in the container.

I think my original statement of the issue didn't clearly state the
underlying reasons.


On Mon, May 9, 2016 at 8:02 AM, Rob Nagler <notifications@github.com> wrote:

> I think we can provide a value add here. I also have some questions:
>
> * How do you like the Jupyter text file editor? It does have emacs
> bindings. Is it too annoying to use going to the file browser?
>

What is the Jupyter text file editor?
You ​mean use %load to bring the code into the next cell?
The file browser looks at my desktop file system, and not at files on the
server.

If you're talking about changes to the notebook itself, then that is not a
problem for me.
I'm happy to modify the notebook using the standard browser UI.

* Would it be useful to have a button for checking out a github repo, or
> maybe some other connection in the UI to GitHub?
>

​A really powerful feature (not related to the original issue) would be to
load notebooks directly from GitHub (or any public git repository)​.
This feature alone would be really great.

A great add-on to the above would be the ability to push the modified
notebook to a git repository.
This raises other difficult issues, however, like whether outputs should be
excluded from the notebook before the commit/push.

Not sure this particular issue/thread is a great venue for such a
discussion.


> * With GitHub, we can actually integrate to push into the repo. This would
> be giving more permissions to the (web) app. Would you want this, or would
> you want to type your credentials each time? You might be able to setup an
> API key per repo, but if not, it would be granting to all repos.
>

​Again, the original issue was not about integrating​ changes in the
notebook itself with GitHub.
This is, of course, an important issue.

Here's what I'm doing now:
1) clone GitHub repo to my local machine
2) use 'upload' button from Jupyter home page to grab notebook from the
local file system
3) modify the notebook using standard browser-based UI
4) save/checkpoint frequently
5) occasionally, execute these steps to archive changes:
   a) select  Kernel -> Restart & Clear Output
   b) select  File -> Download as -> notebook
   c) *.ipnb file appears in browser download folder
   d) copy downloaded file to correct location on local file system
   e) git commit/push on local computer
6) resume work on the Jupyter server

Clearly, it would be nice to integrate that workflow into Jupyter, if
possible.

Step 5a) is important to me.
Without it, the GitHub repository will quickly bloat with unimportant
changes to the outputs.
Sometimes, maybe the changes in the output are important to document, but I
think mostly not.

The value add is: Improving the facilities for developing Python/etc. (not
> notebook) apps in browser, similar to PyCharm but in a notebook style. It's
> something that's missing from Jupyter.
>

​Seems like a good idea.

David
​

**Comment by robnagler** [comment]
Let's chat about this. There is a text editor in Jupyter, but now it's
unclear what you want.

GitHub renders notebooks directly, e.g. rsynergia-linear-8-2-IOTA-SC 20
<https://github.com/radiasoft/rssynergia/blob/master/examples/rssynergia-linear-8-2-IOTA-SC%20.ipynb>.
One thought I had is creating a site like https://bl.ocks.org/ which uses
GitHub (gists, but that's irrelevant for now) as a backing store. (For fun,
I just bought jupyter.run and jupyter.site to allow us to offer shortlinks
or notebooks execution.)
