### ISSUE TITLE
Add pdflatex to beamsim

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#34]
per @mrakitin's request

**Comment by robnagler** [comment]
Can't do this right now due to #36.

**Comment by elventear** [comment]
Do we want the entire texlive distribution or just the pdflatex executable?

**Comment by dtabell** [comment]
What do you need to do?
All of texlive is pretty big; but I think just the pdflatex executable
means you miss a lot of the functionality that comes with the packages.
There are minimal versions of texlive—meaning they include the more
important or commonly used packages—for installing on systems with limited
storage, and one of those might suffice.

**Comment by robnagler** [comment]
@mrakitin it's been a while since this request. What do you want pdflatex for?

**Comment by mrakitin** [comment]
I wanted to save an IPython notebook as a pdf on the Jupiter server, but got this error:
![a](https://cloud.githubusercontent.com/assets/13209176/21268938/c6a49bce-c37e-11e6-9a39-f21d3baaacdf.jpg)

**Comment by robnagler** [comment]
@elventear add the necessary rpms to beamsim-jupyter, since it's only needed for Jupyter. You can't just add the pdflatex binary. It's going to make a fat image, but there's really nothing we can do about it.
