### ISSUE TITLE
make beamsim-jupyter work with python3(?)

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#35]
See jupyterhub/jupyterhub#616. Needs a bit of work. radiasoft/beamsim only has py2.

**Comment by elventear** [comment]
@robnagler  As part of this task, my plan is to run JupyterNotebook using Python 3 (upgrade to the latests versions). And present a Python 2 kernel that will have the environment with the all the codes that we preinstall. 

Should I try to make some of those codes available in Python 3 (if supported at all)?

**Comment by robnagler** [comment]
Only py2 will have the codes. py3 is just for jupyterlab.

**Comment by elventear** [comment]
Merged to changes to `master`.

**Comment by elventear** [comment]
New containers online.
