### ISSUE TITLE
Update to `warp.init_tools`

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#47]
Depends on fix to radiasoft/sirepo#472.  Remi emailed that warp init tools are no part of warp. We need to switch to a specific commit. We should add the uninstall (see below) to support existing VM updates.

Remi writes:

> In order to use the new initialization tools from Warp:
> 
> Update your version of Warp (using git pull and make install) In your input scripts, replace the line
> 
> ``` python
> from warp_init_tools import *
> ```
> 
> by
> 
> ``` python
> from warp.init_tools import *
> ```
> 
> (Notice the . instead of _.)
> It is also recommended that you uninstall the old package warp_init_tools:
> 
> ``` sh
> pip uninstall warp_init_tools
> ```

**Comment by elventear** [comment]
Issue number and repo confusion, should not be closed.

**Comment by robnagler** [comment]
I don't see this as pressing, since nobody seems to complain about it.
