### ISSUE TITLE
build latest shadow

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#56]
shadow build needs to pull from main repo and patch pypi changes

**Comment by robnagler** [comment]
@moellep LMK if you want me to install the latest shadow. It's a bit of work, because I have to port the pypi changes from the official repo.

**Comment by moellep** [comment]
Yes, it would be good, but it isn't critical. I do notice some differences
in reports when comparing between the version bundled with Oasys and our
version.

**Comment by robnagler** [comment]
Fix b9d645760da5d443e7e495b61f7465cd12d37b52
