### ISSUE TITLE
Create Terminado init script for beamsim-jupyter container

### ISSUE THREAD

**Issue by elventear** [radiasoft/containers#57]
The the init script should unset the `PYENV_` variables that are set by the `jupyter` venv. 

See radiasoft/jupyter.radiasoft.org@b321c933c3e73f3917398b1902e3688bc4d9beb9. Once this works the previous commit should be rolled back.

**Comment by robnagler** [comment]
There's a problem with just unsetting the variables: $PATH still has ~/.pyenv/version/jupyter/bin in it. I think that's a general bug that may best be solved in home-env, which would eliminate any ~/.pyenv values in $PATH before eval'ing pyenv.

**Comment by robnagler** [comment]
This has been solved a while ago by adding a ~/.post_bivio_bashrc. The environment gets setup right.
