### ISSUE TITLE
Include rsbeams and rsynergia into the radiasoft/rsbeams-jupyter build

### ISSUE THREAD

**Issue by elventear** [radiasoft/containers#64]
`rsbeams` and `rssynergia` get pulled at container startup (radiasoft/jupyter.radiasoft.org@4b15de887d0f06b090ea212ca2c5dbc4c6bd1ff0), find a way to reduce the delay introduced at startup by bundling those codes within the container build phase.

References:
- #24 
- radiasoft/devops#71

**Comment by robnagler** [comment]
Included.
