### ISSUE TITLE
Change default Dockerfile CMD to "su - vagrant"

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#67]
We always need the right environment so we need to run `su - vagrant` to setup the environment

**Comment by elventear** [comment]
I think the right approach is to use the `SHELL` statement and set it to `/bin/bash -l`.

**Comment by robnagler** [comment]
The goal is that `docker run radiasoft/beamsim` logs in as the run user without changing the behavior for images based on radiasoft/beamsim. 

SHELL is used to set the execution context for RUN, CMD, and ENTRYPOINT, that is, it provides the interpreter for those commands, not the commands themselves. We want to use CMD, not ENTRYPOINT, since we want users to be able to override the default command used by `docker run`.

We might want to set USER to vagrant iwc, we would set CMD to `bash -l`. However, this mucks with /radia-run, which fixes up the uid and gid for files in /home/vagrant.

**Comment by robnagler** [comment]
I don't like this solution. There's more work that would need to be done to make this work right including setting up volumes. Better to have curl installer that does the right thing for known images.
