### ISSUE TITLE
add OPAL to the beamsim container

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/containers#76]
http://amas.web.psi.ch/download/OPAL/

Would be good to have this done by the end of June, if possible.

**Comment by robnagler** [comment]
That page is old. This is  the project home page: https://gitlab.psi.ch/OPAL/src/wikis/home

And the source: https://gitlab.psi.ch/OPAL/src.git

**Comment by robnagler** [comment]
Ran into a timeout with Travis. Asked support to extend build time.

**Comment by robnagler** [comment]
Done
