### ISSUE TITLE
Install HYPRE in beamsim

### ISSUE THREAD

**Issue by ncook882** [radiasoft/containers#87]
We would like to support the FLASH code in our containers, so that users on the Jupyter server may run FLASH simulations.

The [FLASH code](http://flash.uchicago.edu/site/flashcode/) is designed to run on Linux with only a few dependences, most of which we already support:
- Python
- F90/C compilers
- MPI
- parallel-enabled HDF5
- HYPRE

[HYPRE](https://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods) is developed at Lawrence Livermore National Laboratory and provides underlying linear algebra and implicit differential equation solvers.

The FLASH code is available for public use, but prospective users must submit a [request form](http://flash.uchicago.edu/site/flashcode/coderequest/) to obtain access to the source code.

A current Ubtuntu image with the necessary dependencies pre-installed can be found on the [dockerhub](https://hub.docker.com/r/icksa/flash4-deps/). It is my understanding the image is designed to be used with a mounted folder containing the necessary FLASH source code for building a simulation.

**Comment by bruhwiler** [comment]
This implies that we can provide a FLASH executable in our containers but not the source code.

**Comment by robnagler** [comment]
https://github.com/radiasoft/download/commit/b4505d3f676d398bea25571a84b13f217055aca9 supports building rpm from codes. There are two rpms: binary and source. We can restrict access to the source rpm for FLASH.

**Comment by robnagler** [comment]
Just to be clear, we don't need the GUI or testing frameworks as show below, just the first item:

> * Code Request: If you are an external user and you are interested in using the FLASH code in your project, you can request access to the code.
> * Download: If you have been through the request process, you can download current and prior versions of the FLASH code here.
> * QuickFlash-1.0.0.tar.bz2; Data analysis library for FLASH HDF5 files; see http://quickflash.sourceforge.net/home/index.html for more information.
> * FLASH3.1_framework.tar.gz Open source versions of the FLASH3 code; primarily includes inheritance structure and setup script
> * FLASH4.2.2_supplementary_units.tar.gz Supplementary units, provided as-is for the FLASH4.2.2 release.
> * Contributed code: Find information and download links for other contributed code here
> * Flash Test downloads; the framework for running unit and regression tests on FLASH, or other codes with similar build process.
> * Visualization downloads
> * FLASH-Interface: GUI binaries for configuring FLASH.
> MISCELLANEOUS
> * Documentation and User Support
> * Publications
> * FLASH Internal

**Comment by ncook882** [comment]
@robnagler that's correct. Assuming the dependencies are installed, only the source code obtained via the code request is necessary for our current FLASH exercises.

**Comment by robnagler** [comment]
It seems to work with just:

```sh
curl -O https://depot.radiasoft.org/foss/hypre-2.11.2.tar.gz
tar xzf hypre-2.11.2.tar.gz

**Comment by robnagler** [comment]
It seems to work with just:

```sh
cd ~/tmp
curl -O https://depot.radiasoft.org/foss/hypre-2.11.2.tar.gz
tar xzf hypre-2.11.2.tar.gz
cd hypre-2.11.2
./configure --prefix=$(pyenv prefix)
make install
```

@ncook882 would you try this in a container to see if FLASH can use that install?

**Comment by ncook882** [comment]
@robnagler hypre installed properly, and I was able to run FLASH with a standard Makefile configuration.

**Comment by robnagler** [comment]
I committed [hypre.sh](https://github.com/radiasoft/download/blob/1ee30e7d47af331faf3c428607ac0756c1bbdb62/installers/rpm-code/codes/hypre.sh) 
which does what we need. We'll need to do some work to configure FLASH for easy install internally. I'll do that when the time comes.
