### ISSUE TITLE
shifter execution failing

### ISSUE THREAD

**Issue by cchall** [radiasoft/containers#94]
@robnagler Looks like I'm still having the Shifter issue

Execution through Shifter seems to be failing. First noticed when execution of elegant failed with rsopt's run script (https://github.com/radiasoft/rsopt/blob/master/rsopt/package_data/shifter_exec.sh).
Just returns:
` /global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/rsopt/package_data/shifter_exec.sh: line 15: exec: elegant: not found `

Tested on login node just gives the same error:
```
hallcc@cori14:~> shifter --image=radiasoft/sirepo:prod /bin/bash /global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/rsopt/package_data/shifter_exec.sh elegant
/global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/rsopt/package_data/shifter_exec.sh: line 15: exec: elegant: not found
```

**Comment by robnagler** [comment]
still failing on alpha. why doesn't umask work?

**Comment by robnagler** [comment]
I think it was a bootstrapping problem. I rebuilt radiasoft/fedora then beamsim. We'll do an alpha sirepo at 4p today.

**Comment by cchall** [comment]
@robnagler Is the new fix available on Shifter radiasoft/sirepo:alpha? I'm still seeing the same problem right now.

**Comment by robnagler** [comment]
We just did another alpha release, and I verified it pulled the right image, and that it finds elegant if you initialize bash with /home/vagrant/.bashrc. Let me know if it works for you.

**Comment by cchall** [comment]
Just tested and it works for me now.

**Comment by robnagler** [comment]
great, thanks. we'll do a prod release next week. for now you can obviously use :alpha.
