### ISSUE TITLE
Radia in Shifter - ImportError: libmpich_gnu_82.so.3

### ISSUE THREAD

**Issue by cchall** [radiasoft/containers#98]
I am trying to run some timing tests with Radia on NERSC but seem to be having trouble importing Radia when using Shifter. In an interactive session if I try`shifter /bin/bash run_shifter.sh python -c 'import radia'` with `run_shifter.sh` as:
```
ulimit -c 0
unset PYTHONPATH
unset PYTHONSTARTUP
export PYENV_ROOT=/home/vagrant/.pyenv
export HOME=/home/vagrant
source /home/vagrant/.bashrc >& /dev/null
eval export HOME=~$USER
if [[ ! $LD_LIBRARY_PATH =~ /usr/lib64/mpich/lib ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib
fi
exec "$@"
```

I get an error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpich_gnu_82.so.3: cannot open shared object file: No such file or directory
```

**Comment by robnagler** [comment]
It's not failing for me. Could you get me the environment?

shifter --image=radiasoft/sirepo:alpha /bin/bash -x run_shifter.sh env|sort > environ

Here's the output of import radia:

```txt
$ shifter --image=radiasoft/sirepo:alpha /bin/bash -x run_shifter.sh python -c 'import radia'
+ [[ -z 1 ]]
+ ulimit -c 0
+ unset PYTHONPATH
+ unset PYTHONSTARTUP
+ export PYENV_ROOT=/home/vagrant/.pyenv
+ PYENV_ROOT=/home/vagrant/.pyenv
+ export HOME=/home/vagrant
+ HOME=/home/vagrant
+ source /home/vagrant/.bashrc
+ eval export 'HOME=~nagler'
++ export HOME=/global/homes/n/nagler
++ HOME=/global/homes/n/nagler
+ [[ ! /usr/lib64/mpich/lib:/home/vagrant/.local/lib =~ /usr/lib64/mpich/lib ]]
+ exec python -c 'import radia'
```

**Comment by cchall** [comment]
Here's the output
[environ_interactive.txt](https://github.com/radiasoft/containers/files/6940008/environ_interactive.txt)

**Comment by robnagler** [comment]
I didn't realize "interactive" meant SLURM interactive (salloc). Sending the environment helped to see that. :)

I was able to reproduce it. For now, remove the three lines of the `if` and replace with:

```sh
export LD_LIBRARY_PATH=/usr/lib64/mpich/lib:/home/vagrant/.local/lib
```

This seems to work, but I didn't test it fully. I put in a ticket at NERSC. Once I find out what needs to be there, I'll fix up home-env to be correct.

**Comment by cchall** [comment]
That fixed the issue for me. 

Do you think the interactive queue environment makes a difference here? I've certainly run into problems in the past where it behaved differently than sbatch jobs (this is how I got into the mess that is https://github.com/radiasoft/rsopt/issues/64). But I had tested in both debug and interactive for this and saw the same import error.

**Comment by robnagler** [comment]
My guess is something changed. Shane is on vacation so we won't hear an answer till next week.

**Comment by cchall** [comment]
It seems like this fix may not actually work. Replacing
```
if [[ ! $LD_LIBRARY_PATH =~ /usr/lib64/mpich/lib ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib
fi
```
with
```
export LD_LIBRARY_PATH=/usr/lib64/mpich/lib:/home/vagrant/.local/lib
```
Did remove the error but it looks like it causes MPI to just start up n separate applications. Printing MPI COMM_WORLD size in a test script with the former gives:
```
$ srun --ntasks=4 shifter /bin/bash run_shifter_orig.sh python mpi.py 
size 4
size 4
size 4
size 4
```
New version:
```
$ srun --ntasks=4 shifter /bin/bash run_shifter.sh python mpi.py 
size 1
size 1
size 1
size 1
```

**Comment by robnagler** [comment]
From Shane: 
> It is still injected. You can disable it with shifter --module none ... Depending on your image you may want to try shifter --module=mpich-cle6.

I'll test this.

**Comment by robnagler** [comment]
The problem is a missing symlink for libmpich_gnu_82.so.3 in /opt/udiImage/modules/mpich/lib64. I asked Shane to fix.

**Comment by robnagler** [comment]
The following could be automated. @cchall if you are stuck, I can help automate. LMK.

From Shane:
> Here is a hacky workaround...

```sh
$ shifter --module=mpich cp -a /opt/udiImage/modules/mpich/ $SCRATCH/
$ mv $SCRATCH/mpich/lib64/dep/libmpich_gnu_82.so.3 $SCRATCH/mpich/lib64/
$ srun --ntasks 2 shifter --image=radiasoft/sirepo:alpha bash case.sh
$ cat case.sh
unset PYTHONPATH
unset PYTHONSTARTUP
export PYENV_ROOT=/home/vagrant/.pyenv
export HOME=/home/vagrant
source /home/vagrant/.bashrc >& /dev/null
eval export HOME=~$USER
export LD_LIBRARY_PATH=$SCRATCH/mpich/lib64:$SCRATCH/mpich/lib64/dep:/home/vagrant/.local/lib
python -c 'import radia'
```

**Comment by cchall** [comment]
@robnagler This seems to be working well for me.
I don't think any automation is needed for right now. Maybe if this is still an issue when we get back to doing work with rsopt and Radia.

**Comment by robnagler** [comment]
Great, thanks for the update. Hopefully they'll get this fixed soon.

**Comment by cchall** [comment]
I think this has been resolved
